[2024-07-03T18:42:18.055+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T18:42:18.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-03T18:42:18.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-03T18:42:18.158+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T18:42:18.276+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-01-12 00:00:00+00:00
[2024-07-03T18:42:18.322+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_csv', 'scheduled__2024-01-12T00:00:00+00:00', '--job-id', '3498', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmp6u651xtw']
[2024-07-03T18:42:18.335+0000] {standard_task_runner.py:91} INFO - Job 3498: Subtask extract_csv
[2024-07-03T18:42:18.337+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T18:42:18.339+0000] {standard_task_runner.py:63} INFO - Started process 195 to run task
[2024-07-03T18:42:18.534+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [running]> on host f9e37e1ce7c7
[2024-07-03T18:42:22.002+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-12T00:00:00+00:00'
[2024-07-03T18:42:22.007+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T18:42:22.104+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-03T18:42:22.111+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T18:42:22.114+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 37, in extract_csv
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-03T18:42:22.199+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_csv, run_id=scheduled__2024-01-12T00:00:00+00:00, execution_date=20240112T000000, start_date=20240703T184218, end_date=20240703T184222
[2024-07-03T18:42:22.288+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3498 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.; 195)
[2024-07-03T18:42:22.371+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T18:42:22.466+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T18:42:22.485+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T18:53:46.042+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T18:53:46.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-03T18:53:46.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-03T18:53:46.158+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T18:53:46.185+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-01-12 00:00:00+00:00
[2024-07-03T18:53:46.210+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T18:53:46.213+0000] {standard_task_runner.py:63} INFO - Started process 431 to run task
[2024-07-03T18:53:46.210+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_csv', 'scheduled__2024-01-12T00:00:00+00:00', '--job-id', '3621', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmpr07z2w6d']
[2024-07-03T18:53:46.215+0000] {standard_task_runner.py:91} INFO - Job 3621: Subtask extract_csv
[2024-07-03T18:53:46.329+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [running]> on host 4b976b6219c4
[2024-07-03T18:53:46.513+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-12T00:00:00+00:00'
[2024-07-03T18:53:46.515+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T18:53:46.548+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-03T18:53:46.549+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T18:53:46.550+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 37, in extract_csv
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-03T18:53:46.583+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_csv, run_id=scheduled__2024-01-12T00:00:00+00:00, execution_date=20240112T000000, start_date=20240703T185346, end_date=20240703T185346
[2024-07-03T18:53:46.609+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3621 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.; 431)
[2024-07-03T18:53:46.631+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T18:53:46.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-04T00:35:36.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T00:35:36.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-04T00:35:36.787+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-04T00:35:36.788+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-04T00:35:36.826+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-01-12 00:00:00+00:00
[2024-07-04T00:35:36.845+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-04T00:35:36.847+0000] {standard_task_runner.py:63} INFO - Started process 411 to run task
[2024-07-04T00:35:36.848+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_csv', 'scheduled__2024-01-12T00:00:00+00:00', '--job-id', '4359', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpb64c3ytt']
[2024-07-04T00:35:36.853+0000] {standard_task_runner.py:91} INFO - Job 4359: Subtask extract_csv
[2024-07-04T00:35:36.963+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [running]> on host 156a1441f464
[2024-07-04T00:35:37.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-12T00:00:00+00:00'
[2024-07-04T00:35:37.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T00:35:37.192+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12
[2024-07-04T00:35:37.198+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-04T00:35:37.199+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T00:35:37.200+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 46, in extract_csv
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-04T00:35:37.225+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_csv, run_id=scheduled__2024-01-12T00:00:00+00:00, execution_date=20240112T000000, start_date=20240704T003536, end_date=20240704T003537
[2024-07-04T00:35:37.253+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4359 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.; 411)
[2024-07-04T00:35:37.307+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T00:35:37.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-04T01:03:37.759+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T01:03:37.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-04T01:03:37.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-07-04T01:03:37.867+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-04T01:03:37.908+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-01-12 00:00:00+00:00
[2024-07-04T01:03:37.932+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-04T01:03:37.928+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_csv', 'scheduled__2024-01-12T00:00:00+00:00', '--job-id', '4655', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpmzxmqrbl']
[2024-07-04T01:03:37.945+0000] {standard_task_runner.py:91} INFO - Job 4655: Subtask extract_csv
[2024-07-04T01:03:37.946+0000] {standard_task_runner.py:63} INFO - Started process 431 to run task
[2024-07-04T01:03:38.110+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-01-12T00:00:00+00:00 [running]> on host 06ddab619e10
[2024-07-04T01:03:38.364+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-12T00:00:00+00:00'
[2024-07-04T01:03:38.369+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T01:03:38.406+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12
[2024-07-04T01:03:38.411+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-04T01:03:38.412+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T01:03:38.413+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 46, in extract_csv
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.
[2024-07-04T01:03:38.439+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_csv, run_id=scheduled__2024-01-12T00:00:00+00:00, execution_date=20240112T000000, start_date=20240704T010337, end_date=20240704T010338
[2024-07-04T01:03:38.480+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4655 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-01-12' returned non-zero exit status 127.; 431)
[2024-07-04T01:03:38.533+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T01:03:38.553+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
