[2024-07-01T01:25:32.591+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T01:25:32.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_northwind.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-01T01:25:32.727+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_northwind.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-01T01:25:32.729+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-01T01:25:32.799+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-03-15 00:00:00+00:00
[2024-07-01T01:25:32.824+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=815) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-01T01:25:32.830+0000] {standard_task_runner.py:63} INFO - Started process 833 to run task
[2024-07-01T01:25:32.828+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_northwind', 'extract_postgres', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '637', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpx35ncgyn']
[2024-07-01T01:25:32.842+0000] {standard_task_runner.py:91} INFO - Job 637: Subtask extract_postgres
[2024-07-01T01:25:33.014+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_northwind.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [running]> on host 05d913303710
[2024-07-01T01:25:33.244+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-07-01T01:25:33.248+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T01:25:33.339+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-01T01:25:33.344+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-csv --job_id=extract_postgres_2024-03-15 && mkdir -p /data/postgres/2024-03-15 && mv /project/output/tap-postgres/*.csv /data/postgres/2024-03-15/']
[2024-07-01T01:25:33.404+0000] {subprocess.py:86} INFO - Output:
[2024-07-01T01:25:33.412+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-07-01T01:25:33.415+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-01T01:25:33.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T01:25:33.448+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-01T01:25:33.460+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_northwind, task_id=extract_postgres, run_id=scheduled__2024-03-15T00:00:00+00:00, execution_date=20240315T000000, start_date=20240701T012532, end_date=20240701T012533
[2024-07-01T01:25:33.607+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 637 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 833)
[2024-07-01T01:25:33.636+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T01:25:33.669+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-01T10:26:39.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T10:26:39.274+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_northwind.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-01T10:26:39.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_northwind.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-01T10:26:39.288+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-01T10:26:39.374+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-03-15 00:00:00+00:00
[2024-07-01T10:26:39.388+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-01T10:26:39.390+0000] {standard_task_runner.py:63} INFO - Started process 6424 to run task
[2024-07-01T10:26:39.388+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_northwind', 'extract_postgres', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '1182', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmp9expw6ws']
[2024-07-01T10:26:39.391+0000] {standard_task_runner.py:91} INFO - Job 1182: Subtask extract_postgres
[2024-07-01T10:26:39.492+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_northwind.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [running]> on host 85c6ea7cd9cf
[2024-07-01T10:26:39.652+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-07-01T10:26:39.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T10:26:39.678+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-01T10:26:39.679+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-csv --job_id=extract_postgres_2024-03-15 && mkdir -p /data/postgres/2024-03-15 && mv /project/output/tap-postgres/*.csv /data/postgres/2024-03-15/']
[2024-07-01T10:26:39.693+0000] {subprocess.py:86} INFO - Output:
[2024-07-01T10:26:39.696+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-07-01T10:26:39.697+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-01T10:26:39.698+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T10:26:39.714+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-01T10:26:39.721+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_northwind, task_id=extract_postgres, run_id=scheduled__2024-03-15T00:00:00+00:00, execution_date=20240315T000000, start_date=20240701T102639, end_date=20240701T102639
[2024-07-01T10:26:39.738+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1182 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 6424)
[2024-07-01T10:26:39.766+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T10:26:39.781+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
