[2024-06-29T13:54:30.933+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T13:54:31.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-29T13:54:31.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-29T13:54:31.020+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T13:54:31.094+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-06-12 00:00:00+00:00
[2024-06-29T13:54:31.106+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1631) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-29T13:54:31.108+0000] {standard_task_runner.py:63} INFO - Started process 1639 to run task
[2024-06-29T13:54:31.106+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag.py', '--cfg-path', '/tmp/tmpnozbft6f']
[2024-06-29T13:54:31.110+0000] {standard_task_runner.py:91} INFO - Job 327: Subtask extract_postgres
[2024-06-29T13:54:31.205+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-06-12T00:00:00+00:00 [running]> on host f661a8cb6e02
[2024-06-29T13:54:31.365+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-29T13:54:31.367+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T13:54:31.403+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-29T13:54:31.404+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-postgres --job_id=extract_postgres']
[2024-06-29T13:54:31.418+0000] {subprocess.py:86} INFO - Output:
[2024-06-29T13:54:31.420+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-29T13:54:31.421+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-29T13:54:31.422+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T13:54:31.438+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-29T13:54:31.446+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240629T135431, end_date=20240629T135431
[2024-06-29T13:54:31.478+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 327 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 1639)
[2024-06-29T13:54:31.524+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T13:54:31.576+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T13:54:31.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
