[2024-07-02T16:51:37.185+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T16:51:37.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-07-02T16:51:37.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-07-02T16:51:37.309+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T16:51:37.436+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-03-28 00:00:00+00:00
[2024-07-02T16:51:37.452+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1699) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T16:51:37.454+0000] {standard_task_runner.py:63} INFO - Started process 1717 to run task
[2024-07-02T16:51:37.452+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_csv', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '1972', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmp78amj2qx']
[2024-07-02T16:51:37.455+0000] {standard_task_runner.py:91} INFO - Job 1972: Subtask extract_csv
[2024-07-02T16:51:37.566+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_csv scheduled__2024-03-28T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T16:51:37.711+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2024-07-02T16:51:37.712+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T16:51:37.738+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:51:37.739+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T16:51:37.740+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 36, in extract_csv
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:51:37.762+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_csv, run_id=scheduled__2024-03-28T00:00:00+00:00, execution_date=20240328T000000, start_date=20240702T165137, end_date=20240702T165137
[2024-07-02T16:51:37.796+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1972 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run' returned non-zero exit status 127.; 1717)
[2024-07-02T16:51:37.831+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T16:51:37.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T16:48:56.572+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T16:48:56.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-07-03T16:48:56.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-07-03T16:48:56.706+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T16:48:56.875+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-03-28 00:00:00+00:00
[2024-07-03T16:48:56.895+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3299) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T16:48:56.894+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_csv', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '2893', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmpshh9omua']
[2024-07-03T16:48:56.898+0000] {standard_task_runner.py:63} INFO - Started process 3312 to run task
[2024-07-03T16:48:56.902+0000] {standard_task_runner.py:91} INFO - Job 2893: Subtask extract_csv
[2024-07-03T16:48:57.057+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_csv scheduled__2024-03-28T00:00:00+00:00 [running]> on host 3c2535f14011
[2024-07-03T16:48:57.413+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2024-07-03T16:48:57.415+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T16:48:57.482+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-03-28' returned non-zero exit status 127.
[2024-07-03T16:48:57.483+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T16:48:57.485+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 38, in extract_csv
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-03-28' returned non-zero exit status 127.
[2024-07-03T16:48:57.512+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_csv, run_id=scheduled__2024-03-28T00:00:00+00:00, execution_date=20240328T000000, start_date=20240703T164856, end_date=20240703T164857
[2024-07-03T16:48:57.620+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2893 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-03-28' returned non-zero exit status 127.; 3312)
[2024-07-03T16:48:57.657+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T16:48:57.680+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
