[2024-07-02T16:56:48.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T16:56:48.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-07-02T16:56:49.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-07-02T16:56:49.017+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T16:56:49.060+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-04-15 00:00:00+00:00
[2024-07-02T16:56:49.084+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1951) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T16:56:49.088+0000] {standard_task_runner.py:63} INFO - Started process 1964 to run task
[2024-07-02T16:56:49.086+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_csv', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '2040', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpxtss4w08']
[2024-07-02T16:56:49.098+0000] {standard_task_runner.py:91} INFO - Job 2040: Subtask extract_csv
[2024-07-02T16:56:49.218+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_csv scheduled__2024-04-15T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T16:56:49.453+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-07-02T16:56:49.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T16:56:49.500+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:56:49.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T16:56:49.503+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 36, in extract_csv
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:56:49.534+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_csv, run_id=scheduled__2024-04-15T00:00:00+00:00, execution_date=20240415T000000, start_date=20240702T165648, end_date=20240702T165649
[2024-07-02T16:56:49.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2040 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run' returned non-zero exit status 127.; 1964)
[2024-07-02T16:56:49.643+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T16:56:49.666+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T16:54:07.033+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T16:54:07.125+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-07-03T16:54:07.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_csv scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-07-03T16:54:07.150+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T16:54:07.396+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-04-15 00:00:00+00:00
[2024-07-03T16:54:07.419+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3648) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T16:54:07.416+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_csv', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '2995', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmpaow92n4z']
[2024-07-03T16:54:07.421+0000] {standard_task_runner.py:63} INFO - Started process 3670 to run task
[2024-07-03T16:54:07.422+0000] {standard_task_runner.py:91} INFO - Job 2995: Subtask extract_csv
[2024-07-03T16:54:07.569+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_csv scheduled__2024-04-15T00:00:00+00:00 [running]> on host 3c2535f14011
[2024-07-03T16:54:07.781+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-07-03T16:54:07.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T16:54:07.835+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-15' returned non-zero exit status 127.
[2024-07-03T16:54:07.837+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T16:54:07.846+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 38, in extract_csv
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-15' returned non-zero exit status 127.
[2024-07-03T16:54:07.888+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_csv, run_id=scheduled__2024-04-15T00:00:00+00:00, execution_date=20240415T000000, start_date=20240703T165407, end_date=20240703T165407
[2024-07-03T16:54:08.103+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2995 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-15' returned non-zero exit status 127.; 3670)
[2024-07-03T16:54:08.132+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T16:54:08.206+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
