[2024-06-29T13:23:35.615+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T13:23:35.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-06-29T13:23:35.690+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-06-29T13:23:35.697+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T13:23:35.749+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-03-18 00:00:00+00:00
[2024-06-29T13:23:35.760+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=778) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-29T13:23:35.759+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-03-18T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag.py', '--cfg-path', '/tmp/tmpbjygg1q8']
[2024-06-29T13:23:35.761+0000] {standard_task_runner.py:63} INFO - Started process 782 to run task
[2024-06-29T13:23:35.762+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask extract_postgres
[2024-06-29T13:23:35.833+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-18T00:00:00+00:00 [running]> on host f661a8cb6e02
[2024-06-29T13:23:35.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-18T00:00:00+00:00'
[2024-06-29T13:23:35.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T13:23:36.007+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-29T13:23:36.009+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-postgres --job_id=extract_postgres']
[2024-06-29T13:23:36.021+0000] {subprocess.py:86} INFO - Output:
[2024-06-29T13:23:36.023+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-29T13:23:36.024+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-29T13:23:36.025+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T13:23:36.040+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-29T13:23:36.047+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-03-18T00:00:00+00:00, execution_date=20240318T000000, start_date=20240629T132335, end_date=20240629T132336
[2024-06-29T13:23:36.065+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 782)
[2024-06-29T13:23:36.097+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T13:23:36.133+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T13:23:36.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
