[2024-07-02T16:51:48.428+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T16:51:48.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-07-02T16:51:48.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-07-02T16:51:48.530+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-02T16:51:48.752+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-04-18 00:00:00+00:00
[2024-07-02T16:51:48.764+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1831) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T16:51:48.766+0000] {standard_task_runner.py:63} INFO - Started process 1841 to run task
[2024-07-02T16:51:48.764+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-04-18T00:00:00+00:00', '--job-id', '2013', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpth1unowc']
[2024-07-02T16:51:48.768+0000] {standard_task_runner.py:91} INFO - Job 2013: Subtask extract_postgres
[2024-07-02T16:51:48.864+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-18T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T16:51:48.989+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-18T00:00:00+00:00'
[2024-07-02T16:51:48.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T16:51:49.015+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:51:49.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T16:51:49.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 28, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:51:49.034+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-04-18T00:00:00+00:00, execution_date=20240418T000000, start_date=20240702T165148, end_date=20240702T165149
[2024-07-02T16:51:49.062+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2013 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.; 1841)
[2024-07-02T16:51:49.103+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T16:51:49.120+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T16:49:06.906+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T16:49:06.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-07-03T16:49:07.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-07-03T16:49:07.011+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T16:49:07.048+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-04-18 00:00:00+00:00
[2024-07-03T16:49:07.066+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3496) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T16:49:07.069+0000] {standard_task_runner.py:63} INFO - Started process 3510 to run task
[2024-07-03T16:49:07.067+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-04-18T00:00:00+00:00', '--job-id', '2958', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmpo3axmpft']
[2024-07-03T16:49:07.072+0000] {standard_task_runner.py:91} INFO - Job 2958: Subtask extract_postgres
[2024-07-03T16:49:07.167+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-18T00:00:00+00:00 [running]> on host 3c2535f14011
[2024-07-03T16:49:07.319+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-18T00:00:00+00:00'
[2024-07-03T16:49:07.320+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T16:49:07.353+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-04-18' returned non-zero exit status 127.
[2024-07-03T16:49:07.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T16:49:07.354+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 29, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-04-18' returned non-zero exit status 127.
[2024-07-03T16:49:07.384+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-04-18T00:00:00+00:00, execution_date=20240418T000000, start_date=20240703T164906, end_date=20240703T164907
[2024-07-03T16:49:07.417+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2958 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-04-18' returned non-zero exit status 127.; 3510)
[2024-07-03T16:49:07.450+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T16:49:07.472+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
