[2024-07-02T16:41:13.005+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T16:41:13.083+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-07-02T16:41:13.099+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-07-02T16:41:13.100+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T16:41:13.183+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-02-27 00:00:00+00:00
[2024-07-02T16:41:13.196+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T16:41:13.195+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '1847', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpgaj1m8o5']
[2024-07-02T16:41:13.199+0000] {standard_task_runner.py:63} INFO - Started process 1236 to run task
[2024-07-02T16:41:13.199+0000] {standard_task_runner.py:91} INFO - Job 1847: Subtask extract_postgres
[2024-07-02T16:41:13.301+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-02-27T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T16:41:13.467+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-07-02T16:41:13.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T16:41:13.504+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:41:13.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T16:41:13.507+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 28, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:41:13.536+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-02-27T00:00:00+00:00, execution_date=20240227T000000, start_date=20240702T164113, end_date=20240702T164113
[2024-07-02T16:41:13.635+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1847 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.; 1236)
[2024-07-02T16:41:13.656+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T16:41:13.712+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T16:41:13.719+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T16:38:31.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T16:38:31.296+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-07-03T16:38:31.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-07-03T16:38:31.332+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T16:38:31.592+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-02-27 00:00:00+00:00
[2024-07-03T16:38:31.647+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2628) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T16:38:31.650+0000] {standard_task_runner.py:63} INFO - Started process 2633 to run task
[2024-07-03T16:38:31.658+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '2699', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmpwa6zzo_0']
[2024-07-03T16:38:31.666+0000] {standard_task_runner.py:91} INFO - Job 2699: Subtask extract_postgres
[2024-07-03T16:38:31.826+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-02-27T00:00:00+00:00 [running]> on host 3c2535f14011
[2024-07-03T16:38:32.147+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-07-03T16:38:32.153+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T16:38:32.202+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-02-27' returned non-zero exit status 127.
[2024-07-03T16:38:32.203+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T16:38:32.204+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 29, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-02-27' returned non-zero exit status 127.
[2024-07-03T16:38:32.241+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-02-27T00:00:00+00:00, execution_date=20240227T000000, start_date=20240703T163831, end_date=20240703T163832
[2024-07-03T16:38:32.299+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2699 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-02-27' returned non-zero exit status 127.; 2633)
[2024-07-03T16:38:32.379+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T16:38:32.414+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
