[2024-07-12T18:16:59.939+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T18:17:00.081+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:17:00.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:17:00.102+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T18:17:00.138+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_customer_customer_demo> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:17:00.172+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_customer_customer_demo', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5410', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpqpvnf5er']
[2024-07-12T18:17:00.177+0000] {standard_task_runner.py:91} INFO - Job 5410: Subtask extract_postgres_customer_customer_demo
[2024-07-12T18:17:00.357+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T18:17:00.365+0000] {standard_task_runner.py:63} INFO - Started process 278 to run task
[2024-07-12T18:17:00.453+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [running]> on host ae84c7ea76bc
[2024-07-12T18:17:00.660+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_customer_customer_demo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:17:00.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T18:17:00.719+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11
[2024-07-12T18:17:00.728+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:17:00.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T18:17:00.730+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:17:00.763+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_customer_customer_demo, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T181700, end_date=20240712T181700
[2024-07-12T18:17:00.836+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5410 for task extract_postgres_customer_customer_demo (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.; 278)
[2024-07-12T18:17:00.881+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T18:17:00.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-12T18:36:57.791+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T18:36:57.862+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:36:57.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:36:57.880+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T18:36:57.914+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_customer_customer_demo> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:36:57.934+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T18:36:57.937+0000] {standard_task_runner.py:63} INFO - Started process 530 to run task
[2024-07-12T18:36:57.934+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_customer_customer_demo', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5517', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpnwbrukl0']
[2024-07-12T18:36:57.939+0000] {standard_task_runner.py:91} INFO - Job 5517: Subtask extract_postgres_customer_customer_demo
[2024-07-12T18:36:58.046+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [running]> on host da29552222cb
[2024-07-12T18:36:58.230+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_customer_customer_demo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:36:58.231+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T18:36:58.262+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11
[2024-07-12T18:36:58.267+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:36:58.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T18:36:58.269+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:36:58.292+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_customer_customer_demo, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T183657, end_date=20240712T183658
[2024-07-12T18:36:58.318+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5517 for task extract_postgres_customer_customer_demo (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.; 530)
[2024-07-12T18:36:58.354+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T18:36:58.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-12T19:09:30.945+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T19:09:31.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:09:31.121+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:09:31.123+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T19:09:31.198+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_customer_customer_demo> on 2024-07-11 00:00:00+00:00
[2024-07-12T19:09:31.228+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=469) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T19:09:31.232+0000] {standard_task_runner.py:63} INFO - Started process 478 to run task
[2024-07-12T19:09:31.228+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_customer_customer_demo', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5618', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpy1qjki8_']
[2024-07-12T19:09:31.249+0000] {standard_task_runner.py:91} INFO - Job 5618: Subtask extract_postgres_customer_customer_demo
[2024-07-12T19:09:31.507+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [running]> on host 5ef7300ef9b1
[2024-07-12T19:09:31.941+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_customer_customer_demo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T19:09:31.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T19:09:32.005+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11
[2024-07-12T19:09:32.018+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-12T19:09:32.024+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T19:09:32.025+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-12T19:09:32.073+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_customer_customer_demo, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T190931, end_date=20240712T190932
[2024-07-12T19:09:32.120+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5618 for task extract_postgres_customer_customer_demo (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.; 478)
[2024-07-12T19:09:32.163+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T19:09:32.211+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T21:53:01.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T21:53:01.804+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T21:53:01.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T21:53:01.825+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-14T21:53:01.907+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_customer_customer_demo> on 2024-07-11 00:00:00+00:00
[2024-07-14T21:53:01.942+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_customer_customer_demo', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5789', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmp8ojo9zm1']
[2024-07-14T21:53:01.957+0000] {standard_task_runner.py:91} INFO - Job 5789: Subtask extract_postgres_customer_customer_demo
[2024-07-14T21:53:02.120+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=548) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T21:53:02.122+0000] {standard_task_runner.py:63} INFO - Started process 565 to run task
[2024-07-14T21:53:02.196+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_customer_customer_demo scheduled__2024-07-11T00:00:00+00:00 [running]> on host ee4b7f7f7c3e
[2024-07-14T21:53:02.573+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_customer_customer_demo' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-14T21:53:02.584+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T21:53:02.623+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11
[2024-07-14T21:53:02.645+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-14T21:53:02.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T21:53:02.653+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.
[2024-07-14T21:53:02.702+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_customer_customer_demo, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240714T215301, end_date=20240714T215302
[2024-07-14T21:53:02.749+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5789 for task extract_postgres_customer_customer_demo (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_customer_customer_demo_2024-07-11' returned non-zero exit status 127.; 565)
[2024-07-14T21:53:02.799+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T21:53:02.863+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T21:53:02.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
