[2024-07-12T18:16:59.939+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T18:17:00.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:17:00.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:17:00.107+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T18:17:00.138+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_us_states> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:17:00.161+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_us_states', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5416', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpb312sa5v']
[2024-07-12T18:17:00.167+0000] {standard_task_runner.py:91} INFO - Job 5416: Subtask extract_postgres_us_states
[2024-07-12T18:17:00.359+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T18:17:00.387+0000] {standard_task_runner.py:63} INFO - Started process 275 to run task
[2024-07-12T18:17:00.479+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [running]> on host ae84c7ea76bc
[2024-07-12T18:17:00.687+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_us_states' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:17:00.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T18:17:00.735+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11
[2024-07-12T18:17:00.746+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:17:00.747+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T18:17:00.749+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:17:00.778+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_us_states, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T181700, end_date=20240712T181700
[2024-07-12T18:17:00.813+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5416 for task extract_postgres_us_states (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.; 275)
[2024-07-12T18:17:00.854+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T18:17:00.867+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-12T18:36:56.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T18:36:56.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:36:56.422+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T18:36:56.423+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T18:36:56.475+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_us_states> on 2024-07-11 00:00:00+00:00
[2024-07-12T18:36:56.502+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_us_states', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5506', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpahhcyrjv']
[2024-07-12T18:36:56.518+0000] {standard_task_runner.py:91} INFO - Job 5506: Subtask extract_postgres_us_states
[2024-07-12T18:36:56.689+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T18:36:56.691+0000] {standard_task_runner.py:63} INFO - Started process 489 to run task
[2024-07-12T18:36:56.694+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [running]> on host da29552222cb
[2024-07-12T18:36:56.893+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_us_states' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T18:36:56.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T18:36:56.933+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11
[2024-07-12T18:36:56.944+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:36:56.946+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T18:36:56.947+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-12T18:36:56.977+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_us_states, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T183656, end_date=20240712T183656
[2024-07-12T18:36:57.006+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5506 for task extract_postgres_us_states (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.; 489)
[2024-07-12T18:36:57.035+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T18:36:57.069+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T18:36:57.072+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-12T19:09:30.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T19:09:31.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:09:31.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T19:09:31.059+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T19:09:31.103+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_us_states> on 2024-07-11 00:00:00+00:00
[2024-07-12T19:09:31.125+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=462) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-12T19:09:31.125+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_us_states', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5612', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmp214j2okj']
[2024-07-12T19:09:31.130+0000] {standard_task_runner.py:63} INFO - Started process 472 to run task
[2024-07-12T19:09:31.131+0000] {standard_task_runner.py:91} INFO - Job 5612: Subtask extract_postgres_us_states
[2024-07-12T19:09:31.370+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [running]> on host 5ef7300ef9b1
[2024-07-12T19:09:31.782+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_us_states' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T19:09:31.797+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T19:09:31.857+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11
[2024-07-12T19:09:31.866+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-12T19:09:31.867+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T19:09:31.868+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-12T19:09:31.932+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_us_states, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T190931, end_date=20240712T190931
[2024-07-12T19:09:31.991+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5612 for task extract_postgres_us_states (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.; 472)
[2024-07-12T19:09:32.037+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T19:09:32.083+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T21:52:58.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T21:52:58.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T21:52:58.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T21:52:58.682+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-14T21:52:58.771+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres_us_states> on 2024-07-11 00:00:00+00:00
[2024-07-14T21:52:58.825+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=505) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T21:52:58.829+0000] {standard_task_runner.py:63} INFO - Started process 519 to run task
[2024-07-14T21:52:58.826+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_postgres_us_states', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '5766', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpyoz7kaqa']
[2024-07-14T21:52:58.835+0000] {standard_task_runner.py:91} INFO - Job 5766: Subtask extract_postgres_us_states
[2024-07-14T21:52:59.032+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_postgres_us_states scheduled__2024-07-11T00:00:00+00:00 [running]> on host ee4b7f7f7c3e
[2024-07-14T21:52:59.379+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_postgres_us_states' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-14T21:52:59.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T21:52:59.426+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11
[2024-07-14T21:52:59.485+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-14T21:52:59.487+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T21:52:59.493+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 40, in extract_postgres_table
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.
[2024-07-14T21:52:59.580+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline_northwind, task_id=extract_postgres_us_states, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240714T215258, end_date=20240714T215259
[2024-07-14T21:52:59.614+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5766 for task extract_postgres_us_states (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_us_states_2024-07-11' returned non-zero exit status 127.; 519)
[2024-07-14T21:52:59.650+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T21:52:59.731+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T21:52:59.760+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
