[2024-06-29T13:03:08.843+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T13:03:08.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-06-29T13:03:08.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-06-29T13:03:08.952+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T13:03:09.041+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-01-05 00:00:00+00:00
[2024-06-29T13:03:09.055+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag.py', '--cfg-path', '/tmp/tmp12gsaxlw']
[2024-06-29T13:03:09.059+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract_postgres
[2024-06-29T13:03:09.067+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-29T13:03:09.069+0000] {standard_task_runner.py:63} INFO - Started process 179 to run task
[2024-06-29T13:03:09.152+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-05T00:00:00+00:00 [running]> on host f661a8cb6e02
[2024-06-29T13:03:09.345+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-06-29T13:03:09.347+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T13:03:09.384+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-29T13:03:09.386+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-postgres --job_id=extract_postgres']
[2024-06-29T13:03:09.405+0000] {subprocess.py:86} INFO - Output:
[2024-06-29T13:03:09.409+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-29T13:03:09.410+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-29T13:03:09.412+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T13:03:09.430+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-29T13:03:09.439+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-01-05T00:00:00+00:00, execution_date=20240105T000000, start_date=20240629T130308, end_date=20240629T130309
[2024-06-29T13:03:09.465+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 179)
[2024-06-29T13:03:09.487+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T13:03:09.538+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T13:03:09.540+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-30T18:09:24.803+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T18:09:24.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-06-30T18:09:24.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-06-30T18:09:24.915+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-30T18:09:24.987+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-01-05 00:00:00+00:00
[2024-06-30T18:09:25.002+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpnzhasj75']
[2024-06-30T18:09:25.008+0000] {standard_task_runner.py:91} INFO - Job 377: Subtask extract_postgres
[2024-06-30T18:09:25.016+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1672) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-30T18:09:25.018+0000] {standard_task_runner.py:63} INFO - Started process 1679 to run task
[2024-06-30T18:09:25.095+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-05T00:00:00+00:00 [running]> on host 59a47d9254b0
[2024-06-30T18:09:25.258+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-06-30T18:09:25.260+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T18:09:25.290+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-30T18:09:25.291+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-csv --job_id=extract_postgres_2024-01-05 && mv ./output/tap-postgres/*.csv /data/postgres/{table}/2024-01-05/']
[2024-06-30T18:09:25.305+0000] {subprocess.py:86} INFO - Output:
[2024-06-30T18:09:25.307+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-30T18:09:25.308+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-30T18:09:25.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T18:09:25.324+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-30T18:09:25.330+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-01-05T00:00:00+00:00, execution_date=20240105T000000, start_date=20240630T180924, end_date=20240630T180925
[2024-06-30T18:09:25.377+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 377 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 1679)
[2024-06-30T18:09:25.393+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-30T18:09:25.436+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T18:09:25.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
