[2024-07-02T16:56:50.570+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T16:56:50.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-20T00:00:00+00:00 [queued]>
[2024-07-02T16:56:50.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-20T00:00:00+00:00 [queued]>
[2024-07-02T16:56:50.658+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T16:56:50.692+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-04-20 00:00:00+00:00
[2024-07-02T16:56:50.707+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1988) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T16:56:50.710+0000] {standard_task_runner.py:63} INFO - Started process 1998 to run task
[2024-07-02T16:56:50.707+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-04-20T00:00:00+00:00', '--job-id', '2050', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmp8h0gl776']
[2024-07-02T16:56:50.711+0000] {standard_task_runner.py:91} INFO - Job 2050: Subtask extract_postgres
[2024-07-02T16:56:50.798+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-20T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T16:56:50.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-20T00:00:00+00:00'
[2024-07-02T16:56:50.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T16:56:50.961+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:56:50.962+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T16:56:50.964+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 28, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:56:50.984+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-04-20T00:00:00+00:00, execution_date=20240420T000000, start_date=20240702T165650, end_date=20240702T165650
[2024-07-02T16:56:51.005+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2050 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.; 1998)
[2024-07-02T16:56:51.047+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T16:56:51.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T16:54:09.245+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T16:54:09.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-20T00:00:00+00:00 [queued]>
[2024-07-03T16:54:09.342+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-20T00:00:00+00:00 [queued]>
[2024-07-03T16:54:09.343+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T16:54:09.369+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-04-20 00:00:00+00:00
[2024-07-03T16:54:09.380+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3709) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T16:54:09.382+0000] {standard_task_runner.py:63} INFO - Started process 3722 to run task
[2024-07-03T16:54:09.380+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-04-20T00:00:00+00:00', '--job-id', '3015', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmpjadnq0_j']
[2024-07-03T16:54:09.384+0000] {standard_task_runner.py:91} INFO - Job 3015: Subtask extract_postgres
[2024-07-03T16:54:09.467+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-04-20T00:00:00+00:00 [running]> on host 3c2535f14011
[2024-07-03T16:54:09.604+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-20T00:00:00+00:00'
[2024-07-03T16:54:09.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T16:54:09.628+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-04-20' returned non-zero exit status 127.
[2024-07-03T16:54:09.629+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T16:54:09.630+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 29, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-04-20' returned non-zero exit status 127.
[2024-07-03T16:54:09.647+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-04-20T00:00:00+00:00, execution_date=20240420T000000, start_date=20240703T165409, end_date=20240703T165409
[2024-07-03T16:54:09.663+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3015 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-04-20' returned non-zero exit status 127.; 3722)
[2024-07-03T16:54:09.678+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T16:54:09.703+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T16:54:09.705+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
