[2024-07-03T19:30:49.928+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:30:50.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-04-29T00:00:00+00:00 [queued]>
[2024-07-03T19:30:50.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-04-29T00:00:00+00:00 [queued]>
[2024-07-03T19:30:50.034+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T19:30:50.070+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-04-29 00:00:00+00:00
[2024-07-03T19:30:50.084+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T19:30:50.087+0000] {standard_task_runner.py:63} INFO - Started process 1294 to run task
[2024-07-03T19:30:50.083+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_csv', 'scheduled__2024-04-29T00:00:00+00:00', '--job-id', '4027', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmputo5ude7']
[2024-07-03T19:30:50.088+0000] {standard_task_runner.py:91} INFO - Job 4027: Subtask extract_csv
[2024-07-03T19:30:50.191+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-04-29T00:00:00+00:00 [running]> on host 76916b664cf5
[2024-07-03T19:30:50.352+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T00:00:00+00:00'
[2024-07-03T19:30:50.353+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:30:50.388+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29
[2024-07-03T19:30:50.393+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29' returned non-zero exit status 127.
[2024-07-03T19:30:50.393+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:30:50.394+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 46, in extract_csv
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29' returned non-zero exit status 127.
[2024-07-03T19:30:50.420+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_pipeline_northwind, task_id=extract_csv, run_id=scheduled__2024-04-29T00:00:00+00:00, execution_date=20240429T000000, start_date=20240703T193050, end_date=20240703T193050
[2024-07-03T19:30:50.446+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4027 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29' returned non-zero exit status 127.; 1294)
[2024-07-03T19:30:50.464+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:30:50.506+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:30:50.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-04T01:34:58.343+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T01:34:58.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-04-29T00:00:00+00:00 [queued]>
[2024-07-04T01:34:58.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-04-29T00:00:00+00:00 [queued]>
[2024-07-04T01:34:58.428+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-04T01:34:58.465+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-04-29 00:00:00+00:00
[2024-07-04T01:34:58.484+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1948) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-04T01:34:58.486+0000] {standard_task_runner.py:63} INFO - Started process 1965 to run task
[2024-07-04T01:34:58.483+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline_northwind', 'extract_csv', 'scheduled__2024-04-29T00:00:00+00:00', '--job-id', '5058', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_northwind.py', '--cfg-path', '/tmp/tmpbjgu7iu6']
[2024-07-04T01:34:58.487+0000] {standard_task_runner.py:91} INFO - Job 5058: Subtask extract_csv
[2024-07-04T01:34:58.599+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline_northwind.extract_csv scheduled__2024-04-29T00:00:00+00:00 [running]> on host 06ddab619e10
[2024-07-04T01:34:58.751+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T00:00:00+00:00'
[2024-07-04T01:34:58.752+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T01:34:58.773+0000] {logging_mixin.py:188} INFO - Running command: meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29
[2024-07-04T01:34:58.776+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29' returned non-zero exit status 127.
[2024-07-04T01:34:58.777+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T01:34:58.778+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_pipeline_northwind.py", line 46, in extract_csv
    result = subprocess.run(extract_command, shell=True, check=True, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29' returned non-zero exit status 127.
[2024-07-04T01:34:58.797+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_pipeline_northwind, task_id=extract_csv, run_id=scheduled__2024-04-29T00:00:00+00:00, execution_date=20240429T000000, start_date=20240704T013458, end_date=20240704T013458
[2024-07-04T01:34:58.815+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5058 for task extract_csv (Command 'meltano elt tap-csv target-csv --transform=run --job_id=extract_csv_2024-04-29' returned non-zero exit status 127.; 1965)
[2024-07-04T01:34:58.826+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T01:34:58.841+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
