[2024-06-29T13:33:43.397+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T13:33:43.458+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-06-29T13:33:43.471+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-06-29T13:33:43.472+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-29T13:33:43.603+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-03-22 00:00:00+00:00
[2024-06-29T13:33:43.619+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=986) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-29T13:33:43.621+0000] {standard_task_runner.py:63} INFO - Started process 990 to run task
[2024-06-29T13:33:43.618+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag.py', '--cfg-path', '/tmp/tmpl9lgnw07']
[2024-06-29T13:33:43.623+0000] {standard_task_runner.py:91} INFO - Job 180: Subtask extract_postgres
[2024-06-29T13:33:43.708+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-22T00:00:00+00:00 [running]> on host f661a8cb6e02
[2024-06-29T13:33:43.833+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-06-29T13:33:43.835+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T13:33:43.861+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-29T13:33:43.862+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-postgres --job_id=extract_postgres']
[2024-06-29T13:33:43.881+0000] {subprocess.py:86} INFO - Output:
[2024-06-29T13:33:43.884+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-29T13:33:43.885+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-29T13:33:43.886+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T13:33:43.907+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-29T13:33:43.916+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-03-22T00:00:00+00:00, execution_date=20240322T000000, start_date=20240629T133343, end_date=20240629T133343
[2024-06-29T13:33:44.106+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 180 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 990)
[2024-06-29T13:33:44.158+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T13:33:44.175+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
