[2024-07-02T16:46:26.039+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T16:46:26.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-02T16:46:26.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-02T16:46:26.151+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T16:46:26.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-03-15 00:00:00+00:00
[2024-07-02T16:46:26.219+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1479) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T16:46:26.219+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '1919', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpw4gzgjuc']
[2024-07-02T16:46:26.223+0000] {standard_task_runner.py:63} INFO - Started process 1494 to run task
[2024-07-02T16:46:26.224+0000] {standard_task_runner.py:91} INFO - Job 1919: Subtask extract_postgres
[2024-07-02T16:46:26.383+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T16:46:26.619+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-07-02T16:46:26.624+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T16:46:26.668+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:46:26.674+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T16:46:26.676+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 28, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T16:46:26.720+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-03-15T00:00:00+00:00, execution_date=20240315T000000, start_date=20240702T164626, end_date=20240702T164626
[2024-07-02T16:46:26.757+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1919 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.; 1494)
[2024-07-02T16:46:26.777+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T16:46:26.839+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T16:46:26.849+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T16:43:48.749+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T16:43:48.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-03T16:43:48.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-07-03T16:43:48.885+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T16:43:48.929+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-03-15 00:00:00+00:00
[2024-07-03T16:43:48.948+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3007) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-03T16:43:48.953+0000] {standard_task_runner.py:63} INFO - Started process 3027 to run task
[2024-07-03T16:43:48.948+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '2816', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag_teste.py', '--cfg-path', '/tmp/tmp9t4n8fih']
[2024-07-03T16:43:48.956+0000] {standard_task_runner.py:91} INFO - Job 2816: Subtask extract_postgres
[2024-07-03T16:43:49.091+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-03-15T00:00:00+00:00 [running]> on host 3c2535f14011
[2024-07-03T16:43:49.305+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-07-03T16:43:49.307+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T16:43:49.342+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-03-15' returned non-zero exit status 127.
[2024-07-03T16:43:49.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T16:43:49.344+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_dag_teste.py", line 29, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-03-15' returned non-zero exit status 127.
[2024-07-03T16:43:49.368+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-03-15T00:00:00+00:00, execution_date=20240315T000000, start_date=20240703T164348, end_date=20240703T164349
[2024-07-03T16:43:49.387+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2816 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run --job_id=extract_postgres_2024-03-15' returned non-zero exit status 127.; 3027)
[2024-07-03T16:43:49.421+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T16:43:49.457+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T16:43:49.459+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
