[2024-06-29T13:03:09.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T13:03:09.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-06-29T13:03:09.304+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-06-29T13:03:09.305+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T13:03:09.345+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-01-06 00:00:00+00:00
[2024-06-29T13:03:09.359+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag.py', '--cfg-path', '/tmp/tmppre9n6ln']
[2024-06-29T13:03:09.363+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask extract_postgres
[2024-06-29T13:03:09.369+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-29T13:03:09.371+0000] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2024-06-29T13:03:09.463+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-06T00:00:00+00:00 [running]> on host f661a8cb6e02
[2024-06-29T13:03:09.615+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-06-29T13:03:09.616+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T13:03:09.640+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-29T13:03:09.641+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-postgres --job_id=extract_postgres']
[2024-06-29T13:03:09.655+0000] {subprocess.py:86} INFO - Output:
[2024-06-29T13:03:09.657+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-29T13:03:09.658+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-29T13:03:09.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T13:03:09.672+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-29T13:03:09.680+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-01-06T00:00:00+00:00, execution_date=20240106T000000, start_date=20240629T130309, end_date=20240629T130309
[2024-06-29T13:03:09.710+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 186)
[2024-06-29T13:03:09.748+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T13:03:09.786+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T13:03:09.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-30T18:09:25.196+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T18:09:25.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-06-30T18:09:25.326+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-06-30T18:09:25.327+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-30T18:09:25.372+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-01-06 00:00:00+00:00
[2024-06-30T18:09:25.385+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpng5n9va6']
[2024-06-30T18:09:25.388+0000] {standard_task_runner.py:91} INFO - Job 379: Subtask extract_postgres
[2024-06-30T18:09:25.393+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1675) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-30T18:09:25.395+0000] {standard_task_runner.py:63} INFO - Started process 1692 to run task
[2024-06-30T18:09:25.465+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-01-06T00:00:00+00:00 [running]> on host 59a47d9254b0
[2024-06-30T18:09:25.584+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-06-30T18:09:25.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T18:09:25.617+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-30T18:09:25.618+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-csv --job_id=extract_postgres_2024-01-06 && mv ./output/tap-postgres/*.csv /data/postgres/{table}/2024-01-06/']
[2024-06-30T18:09:25.631+0000] {subprocess.py:86} INFO - Output:
[2024-06-30T18:09:25.634+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-30T18:09:25.635+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-30T18:09:25.636+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T18:09:25.652+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-30T18:09:25.660+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-01-06T00:00:00+00:00, execution_date=20240106T000000, start_date=20240630T180925, end_date=20240630T180925
[2024-06-30T18:09:25.787+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 379 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 1692)
[2024-06-30T18:09:25.811+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-30T18:09:25.857+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T18:09:25.859+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
