[2024-07-01T10:57:38.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T10:57:38.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_northwind.extract_csv scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-07-01T10:57:38.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_northwind.extract_csv scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-07-01T10:57:38.410+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-01T10:57:38.459+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_csv> on 2024-06-23 00:00:00+00:00
[2024-07-01T10:57:38.479+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8267) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-01T10:57:38.482+0000] {standard_task_runner.py:63} INFO - Started process 8283 to run task
[2024-07-01T10:57:38.484+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_northwind', 'extract_csv', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '1575', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpayx9u8c8']
[2024-07-01T10:57:38.495+0000] {standard_task_runner.py:91} INFO - Job 1575: Subtask extract_csv
[2024-07-01T10:57:38.666+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_northwind.extract_csv scheduled__2024-06-23T00:00:00+00:00 [running]> on host 85c6ea7cd9cf
[2024-07-01T10:57:38.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_northwind' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-07-01T10:57:38.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T10:57:38.893+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-01T10:57:38.894+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-csv target-csv --job_id=extract_csv_2024-06-23 && mkdir -p /data/csv/2024-06-23 && mv /project/output/tap-csv/*.csv /data/csv/2024-06-23/']
[2024-07-01T10:57:38.907+0000] {subprocess.py:86} INFO - Output:
[2024-07-01T10:57:38.909+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-07-01T10:57:38.910+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-01T10:57:38.911+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T10:57:38.928+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-01T10:57:38.935+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_northwind, task_id=extract_csv, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240701T105738, end_date=20240701T105738
[2024-07-01T10:57:38.952+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1575 for task extract_csv (Bash command failed. The command returned a non-zero exit code 127.; 8283)
[2024-07-01T10:57:38.976+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T10:57:39.011+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T10:57:39.016+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
