[2024-07-02T17:02:09.206+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T17:02:09.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-07-02T17:02:09.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.extract_postgres scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-07-02T17:02:09.323+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-02T17:02:09.474+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_postgres> on 2024-05-14 00:00:00+00:00
[2024-07-02T17:02:09.491+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T17:02:09.490+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_dag', 'extract_postgres', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '2129', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmpvohvhl70']
[2024-07-02T17:02:09.493+0000] {standard_task_runner.py:63} INFO - Started process 2291 to run task
[2024-07-02T17:02:09.494+0000] {standard_task_runner.py:91} INFO - Job 2129: Subtask extract_postgres
[2024-07-02T17:02:09.597+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_dag.extract_postgres scheduled__2024-05-14T00:00:00+00:00 [running]> on host ee7e13960694
[2024-07-02T17:02:09.746+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-07-02T17:02:09.748+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T17:02:09.777+0000] {logging_mixin.py:188} INFO - Command failed with error: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T17:02:09.777+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T17:02:09.778+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_northwind.py", line 28, in extract_postgres
    subprocess.run(extract_command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.
[2024-07-02T17:02:09.805+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=extract_postgres, run_id=scheduled__2024-05-14T00:00:00+00:00, execution_date=20240514T000000, start_date=20240702T170209, end_date=20240702T170209
[2024-07-02T17:02:09.956+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2129 for task extract_postgres (Command 'meltano elt tap-postgres target-csv --transform=run' returned non-zero exit status 127.; 2291)
[2024-07-02T17:02:09.993+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T17:02:10.037+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T17:02:10.040+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
