[2024-06-29T13:28:43.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T13:28:43.466+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-06-29T13:28:43.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-06-29T13:28:43.480+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T13:28:43.506+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2024-03-28 00:00:00+00:00
[2024-06-29T13:28:43.522+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=908) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-29T13:28:43.520+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'northwind_dag', 'extract_postgres', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/northwind_dag.py', '--cfg-path', '/tmp/tmpw562lup8']
[2024-06-29T13:28:43.524+0000] {standard_task_runner.py:63} INFO - Started process 915 to run task
[2024-06-29T13:28:43.524+0000] {standard_task_runner.py:91} INFO - Job 171: Subtask extract_postgres
[2024-06-29T13:28:43.616+0000] {task_command.py:426} INFO - Running <TaskInstance: northwind_dag.extract_postgres scheduled__2024-03-28T00:00:00+00:00 [running]> on host f661a8cb6e02
[2024-06-29T13:28:43.752+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='northwind_dag' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2024-06-29T13:28:43.753+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T13:28:43.781+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-29T13:28:43.782+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano elt tap-postgres target-postgres --job_id=extract_postgres']
[2024-06-29T13:28:43.798+0000] {subprocess.py:86} INFO - Output:
[2024-06-29T13:28:43.800+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-06-29T13:28:43.801+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-29T13:28:43.803+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T13:28:43.818+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-29T13:28:43.826+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind_dag, task_id=extract_postgres, run_id=scheduled__2024-03-28T00:00:00+00:00, execution_date=20240328T000000, start_date=20240629T132843, end_date=20240629T132843
[2024-06-29T13:28:43.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 171 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 127.; 915)
[2024-06-29T13:28:43.941+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T13:28:43.983+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T13:28:43.986+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
